//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gemeente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gemeente()
        {
            this.Klant = new HashSet<Klant>();
            this.Leverancier = new HashSet<Leverancier>();
        }
    
        public int PostcodeID { get; set; }
        public Nullable<int> Postcode { get; set; }
        public string Gemeente1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Klant> Klant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leverancier> Leverancier { get; set; }
        public override string ToString()
        {
            return $"{Postcode} {Gemeente1}";
        }
    }
}
