//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeelslid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personeelslid()
        {
            this.Bestelling = new HashSet<Bestelling>();
        }
    
        public int PersoneelslidID { get; set; }
        public string Voornaam { get; set; }
        public string Achternaam { get; set; }
        public Nullable<int> FunctieID { get; set; }
        public string Username { get; set; }
        public string Pass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestelling> Bestelling { get; set; }
        public virtual Functie Functie { get; set; }

        public override string ToString()
        {
            return $"{Voornaam} {Achternaam}";
        }
    }
}
