//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.BestellingProduct = new HashSet<BestellingProduct>();
        }
    
        public int ProductID { get; set; }
        public string Naam { get; set; }
        public Nullable<int> Marge { get; set; }
        public Nullable<double> Inkoopprijs { get; set; }
        public string Eenheid { get; set; }
        public Nullable<int> BTW { get; set; }
        public Nullable<int> LeverancierID { get; set; }
        public Nullable<int> CategorieID { get; set; }
        public string EanCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BestellingProduct> BestellingProduct { get; set; }
        public virtual Categorie Categorie { get; set; }
        public virtual Leverancier Leverancier { get; set; }
        public override string ToString()
        {
            return Naam;
        }

        public double totaalInclBtw
        {
            get
            {
                return (double)(Inkoopprijs + (Inkoopprijs * ((double)BTW / 100)));
            }
        }

        public double Verkoopprijs
        {
            get
            {
                return (double)(Inkoopprijs + (Inkoopprijs * ((double)Marge / 100)));
            }
        }
        public double totaalVerkoopInclBtw
        {
            get
            {
                return (double)(Verkoopprijs + (Verkoopprijs * ((double)BTW / 100)));
            }
        }
    }
}
